version: '3'

services:
        app_be: 
          build: 
            context: .
            dockerfile: Dockerfile.dev
          ports:
            - "4000:4000"
          volumes: 
            - .:/usr/src/app
